before_script:
#  - npm install

stages:
  - lint
  - test
  - build
  - deploy

test:
  stage: test
  script:
#    - npm run test
     - echo "run test "


lint:
  stage: lint
  script:
#    - npm run lint
    - echo "run lint"


build:
  stage: build
  script:
    # npm install 測試完畢移到before scripts
    - npm install
    - npm run build -- -prod
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    expire_in: "2 days"
    untracked: true
    paths:
    - dist/
  only:
    - master

pages:
  stage: deploy
  script:
    # npm install 測試完畢移到before scripts
    - npm install
    - npm run build -- --base-href /$CI_PROJECT_NAME/ --output-path public
  artifacts:
    paths:
    - public/
  only:
    - master
