import { AfterViewInit, ChangeDetectorRef, ElementRef, EventEmitter, Injector, OnChanges, OnDestroy, OnInit, Renderer2, SimpleChanges, TemplateRef, Type, ViewContainerRef } from '@angular/core';
import { FocusTrap, FocusTrapFactory } from '@angular/cdk/a11y';
import { Overlay, OverlayRef } from '@angular/cdk/overlay';
import { CdkPortalOutlet, TemplatePortal } from '@angular/cdk/portal';
import { Observable, Subject } from 'rxjs';
import { DwScrollStrategyOptions } from '../core/overlay/scroll/dw-scroll-strategy-options';
import { DwDrawerOptions, DwDrawerPlacement } from './dw-drawer-options';
import { DwDrawerRef } from './dw-drawer-ref';
export declare const DRAWER_ANIMATE_DURATION = 300;
export declare class DwDrawerComponent<T = any, R = any, D = any> extends DwDrawerRef<R> implements OnInit, OnDestroy, AfterViewInit, OnChanges, DwDrawerOptions {
    private document;
    private renderer;
    private overlay;
    private elementRef;
    private injector;
    private changeDetectorRef;
    private focusTrapFactory;
    private dwScrollStrategyOptions;
    private viewContainerRef;
    previouslyFocusedElement: HTMLElement;
    dwContentParams: D;
    overlayRef: OverlayRef;
    portal: TemplatePortal;
    focusTrap: FocusTrap;
    isOpen: boolean;
    templateContext: {
        $implicit: D;
        drawerRef: DwDrawerRef<R>;
    };
    readonly transform: string;
    readonly width: string;
    readonly height: string;
    readonly isLeftOrRight: boolean;
    drawerTemplate: TemplateRef<{}>;
    contentTemplate: TemplateRef<{}>;
    bodyPortalOutlet: CdkPortalOutlet;
    dwContent: TemplateRef<{
        $implicit: D;
        drawerRef: DwDrawerRef<R>;
    }> | Type<T>;
    dwClosable: boolean;
    dwMaskClosable: boolean;
    dwMask: boolean;
    dwTitle: string | TemplateRef<{}>;
    dwPlacement: DwDrawerPlacement;
    dwMaskStyle: object;
    dwBodyStyle: object;
    dwWrapClassName: string;
    dwWidth: number | string;
    dwHeight: number | string;
    dwZIndex: number;
    dwOffsetX: number;
    dwOffsetY: number;
    dwVisible: boolean;
    dwOnViewInit: EventEmitter<void>;
    dwOnClose: EventEmitter<MouseEvent>;
    dwAfterOpen: Subject<void>;
    dwAfterClose: Subject<R>;
    readonly afterOpen: Observable<void>;
    readonly afterClose: Observable<R>;
    isNonEmptyString(value: {}): boolean;
    isTemplateRef(value: {}): boolean;
    constructor(document: any, renderer: Renderer2, overlay: Overlay, elementRef: ElementRef, injector: Injector, changeDetectorRef: ChangeDetectorRef, focusTrapFactory: FocusTrapFactory, dwScrollStrategyOptions: DwScrollStrategyOptions, viewContainerRef: ViewContainerRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    close(result?: R): void;
    open(): void;
    closeClick(): void;
    maskClick(): void;
    private attachBodyContent;
    private attachOverlay;
    private disposeOverlay;
    private getOverlayConfig;
    private updateOverlayStyle;
    private updateBodyOverflow;
    savePreviouslyFocusedElement(): void;
    private trapFocus;
    private restoreFocus;
}
