import { FlexibleConnectedPositionStrategy, Overlay, OverlayConfig, OverlayRef, PositionStrategy } from '@angular/cdk/overlay';
import { TemplatePortal } from '@angular/cdk/portal';
import { AfterViewInit, ChangeDetectorRef, ElementRef, EventEmitter, OnDestroy, OnInit, Renderer2, ViewContainerRef } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { Subscription } from 'rxjs';
import { DwFormatEmitEvent } from '../tree/interface';
import { DwTreeNode } from '../tree/dw-tree-node';
import { DwTreeComponent } from '../tree/dw-tree.component';
export declare class DwTreeSelectComponent implements ControlValueAccessor, OnInit, AfterViewInit, OnDestroy {
    private document;
    private element;
    private renderer;
    private cdr;
    private overlay;
    private viewContainerRef;
    private nodes;
    isComposing: boolean;
    isDestroy: boolean;
    inputValue: string;
    dropDownClassMap: {
        [className: string]: boolean;
    };
    dropDownPosition: 'top' | 'center' | 'bottom';
    overlayRef: OverlayRef;
    portal: TemplatePortal<{}>;
    positionStrategy: FlexibleConnectedPositionStrategy;
    overlayBackdropClickSubscription: Subscription;
    selectionChangeSubscription: Subscription;
    selectedNodes: DwTreeNode[];
    value: string[];
    dwAllowClear: boolean;
    dwShowExpand: boolean;
    dwDropdownMatchSelectWidth: boolean;
    dwCheckable: boolean;
    dwShowSearch: boolean;
    dwDisabled: boolean;
    dwShowLine: boolean;
    dwAsyncData: boolean;
    dwMultiple: boolean;
    dwDefaultExpandAll: boolean;
    dwOpen: boolean;
    dwSize: string;
    dwPlaceHolder: string;
    dwDropdownStyle: {
        [key: string]: string;
    };
    dwDefaultExpandedKeys: string[];
    dwDisplayWith: (node: DwTreeNode) => string;
    dwOpenChange: EventEmitter<boolean>;
    dwCleared: EventEmitter<void>;
    dwRemoved: EventEmitter<DwTreeNode>;
    dwExpandChange: EventEmitter<DwFormatEmitEvent>;
    dwTreeClick: EventEmitter<DwFormatEmitEvent>;
    dwTreeCheckBoxChange: EventEmitter<DwFormatEmitEvent>;
    dwNodes: DwTreeNode[];
    inputElement: ElementRef;
    treeSelect: ElementRef;
    dropdownTemplate: any;
    treeRef: DwTreeComponent;
    onChange: (value: string[] | string) => void;
    onTouched: () => void;
    readonly placeHolderDisplay: string;
    readonly searchDisplay: string;
    readonly isMultiple: boolean;
    readonly selectedValueDisplay: {
        [key: string]: string;
    };
    constructor(document: any, // tslint:disable-line:no-any
    element: ElementRef, renderer: Renderer2, cdr: ChangeDetectorRef, overlay: Overlay, viewContainerRef: ViewContainerRef);
    trigger(): void;
    openDropdown(): void;
    closeDropDown(): void;
    onKeyDownInput(e: KeyboardEvent): void;
    setInputValue(value: string): void;
    detachOverlay(): void;
    removeSelected(node: DwTreeNode, emit?: boolean): void;
    focusOnInput(): void;
    attachOverlay(): void;
    getOverlayConfig(): OverlayConfig;
    getOverlayPosition(): PositionStrategy;
    subscribeOverlayBackdropClick(): Subscription;
    subscribeSelectionChange(): Subscription;
    updateSelectedNodes(): void;
    updatePosition(): void;
    updateInputWidth(): void;
    onClearSelection(): void;
    updateDropDownClassMap(): void;
    updateCdkConnectedOverlayStatus(): void;
    writeValue(value: string[] | string): void;
    registerOnChange(fn: (_: string[] | string) => void): void;
    registerOnTouched(fn: () => void): void;
    ngOnInit(): void;
    ngOnDestroy(): void;
    ngAfterViewInit(): void;
    setDisabledState(isDisabled: boolean): void;
}
