import { AfterViewInit, ChangeDetectorRef, EventEmitter, OnDestroy } from '@angular/core';
import { Subscription } from 'rxjs';
import { DwScrollService } from '../core/scroll/dw-scroll.service';
import { DwAnchorLinkComponent } from './dw-anchor-link.component';
export declare class DwAnchorComponent implements OnDestroy, AfterViewInit {
    private scrollSrv;
    private doc;
    private cd;
    private links;
    private animating;
    private target;
    scroll$: Subscription;
    visible: boolean;
    wrapperStyle: {};
    private wrap;
    private ink;
    private _affix;
    dwAffix: boolean;
    private _bounds;
    dwBounds: number;
    private _offsetTop;
    dwOffsetTop: number;
    private _showInkInFixed;
    dwShowInkInFixed: boolean;
    dwTarget: Element;
    dwClick: EventEmitter<string>;
    dwScroll: EventEmitter<DwAnchorLinkComponent>;
    constructor(scrollSrv: DwScrollService, doc: any, cd: ChangeDetectorRef);
    registerLink(link: DwAnchorLinkComponent): void;
    unregisterLink(link: DwAnchorLinkComponent): void;
    private getTarget;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    private registerScrollEvent;
    private removeListen;
    private getOffsetTop;
    handleScroll(): void;
    private clearActive;
    private handleActive;
    handleScrollTo(linkComp: DwAnchorLinkComponent): void;
}
