import { AfterViewInit, ElementRef, EventEmitter, OnChanges, OnDestroy, OnInit, Renderer2 } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { DwCheckboxWrapperComponent } from './dw-checkbox-wrapper.component';
export declare class DwCheckboxComponent implements OnInit, ControlValueAccessor, OnChanges, AfterViewInit, OnDestroy {
    private elementRef;
    private renderer;
    private dwCheckboxWrapperComponent;
    private _disabled;
    private _indeterminate;
    private _autoFocus;
    private _checked;
    private el;
    private isInit;
    private prefixCls;
    private onChange;
    private onTouched;
    private inputElement;
    contentElement: ElementRef;
    classMap: {};
    dwCheckedChange: EventEmitter<boolean>;
    dwValue: string;
    dwAutoFocus: boolean;
    dwDisabled: boolean;
    dwIndeterminate: boolean;
    dwChecked: boolean;
    onClick(e: MouseEvent): void;
    onBlur(): void;
    updateAutoFocus(): void;
    updateValue(value: boolean): void;
    writeValue(value: boolean): void;
    registerOnChange(fn: (_: boolean) => {}): void;
    registerOnTouched(fn: () => {}): void;
    setDisabledState(isDisabled: boolean): void;
    updateClassMap(): void;
    focus(): void;
    blur(): void;
    checkContent(): void;
    constructor(elementRef: ElementRef, renderer: Renderer2, dwCheckboxWrapperComponent: DwCheckboxWrapperComponent);
    ngOnInit(): void;
    ngOnChanges(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
}
