import { AfterViewInit, ChangeDetectorRef, ElementRef, EventEmitter, NgZone, OnDestroy, OnInit, QueryList, Renderer2, TemplateRef } from '@angular/core';
import { DwMeasureScrollbarService } from '../core/services/dw-measure-scrollbar.service';
import { DwI18nService } from '../i18n/dw-i18n.service';
import { DwThComponent } from './dw-th.component';
import { DwTheadComponent } from './dw-thead.component';
export declare class DwTableComponent implements OnInit, AfterViewInit, OnDestroy {
    private renderer;
    private ngZone;
    private elementRef;
    private cdr;
    private dwMeasureScrollbarService;
    private i18n;
    private unsubscribe$;
    private _bordered;
    private _showPagination;
    private _loading;
    private _showSizeChanger;
    private _showQuickJumper;
    private _hideOnSinglePage;
    private _scroll;
    private _footer;
    private _title;
    private _noResult;
    private _pageIndex;
    private _pageSize;
    private _widthConfig;
    private _frontPagination;
    private _simple;
    locale: any;
    dwTheadComponent: DwTheadComponent;
    isFooterString: boolean;
    isTitleString: boolean;
    isNoResultString: boolean;
    el: HTMLElement;
    lastScrollLeft: number;
    rawData: any[];
    syncData: any[];
    /** public data for ngFor tr */
    data: any[];
    headerBottomStyle: any;
    isWidthConfigSet: boolean;
    tableHeaderElement: ElementRef;
    tableBodyElement: ElementRef;
    tableMainElement: ElementRef;
    listOfDwThComponent: QueryList<DwThComponent>;
    dwPageSizeChange: EventEmitter<number>;
    dwPageIndexChange: EventEmitter<number>;
    dwShowTotal: TemplateRef<{
        $implicit: number;
        range: [number, number];
    }>;
    dwCurrentPageDataChange: EventEmitter<any[]>;
    dwSize: string;
    /** page size changer select values */
    dwPageSizeOptions: number[];
    dwLoadingDelay: number;
    dwTotal: number;
    dwSimple: boolean;
    dwFrontPagination: boolean;
    dwWidthConfig: string[];
    dwTitle: string | TemplateRef<void>;
    dwFooter: string | TemplateRef<void>;
    dwNoResult: string | TemplateRef<void>;
    dwBordered: boolean;
    dwShowPagination: boolean;
    dwLoading: boolean;
    dwShowSizeChanger: boolean;
    dwHideOnSinglePage: boolean;
    dwShowQuickJumper: boolean;
    dwScroll: {
        x: string;
        y: string;
    };
    dwData: any[];
    parseInputData(): void;
    dwPageIndex: number;
    emitPageIndex(index: number): void;
    emitPageSize(size: number): void;
    dwPageSize: number;
    checkPageIndexBounding(): void;
    generateSyncDisplayData(): void;
    syncScrollTable(e: MouseEvent): void;
    setScrollPositionClassName(): void;
    setScrollName(position?: string): void;
    fitScrollBar(): void;
    onWindowResize(): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    constructor(renderer: Renderer2, ngZone: NgZone, elementRef: ElementRef, cdr: ChangeDetectorRef, dwMeasureScrollbarService: DwMeasureScrollbarService, i18n: DwI18nService);
}
